[package]
name = "ascent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_rapier2d = "0.16.2"
bevy_ecs_ldtk = "0.4.0"
